version: 0.2

phases:
  install:
    commands:
      - curl -o /tmp/chefdk.deb https://packages.chef.io/files/current/chefdk/4.0.1/ubuntu/18.04/chefdk_4.0.1-1_amd64.deb
      - dpkg -i /tmp/chefdk.deb
  build:
    commands:
      - /opt/chefdk/bin/cookstyle
      - /opt/chefdk/bin/foodcritic -B ./
      - /opt/chefdk/embedded/bin/rspec
