name 'cbtest'
maintainer 'lynn'
maintainer_email 'lynn@test'
license 'All Rights Reserved'
description 'Installs/Configures cbtest'
long_description 'Installs/Configures cbtest'
version '0.1.0'
chef_version '>= 13.0'
issues_url 'https://github.com/<insert_org_here>/cbtest/issues'
source_url 'https://github.com/lcc2207/cbtest'
supports 'ubuntu', '>= 12.04'
supports 'redhat', '>= 6.5'
supports 'centos', '>= 6.5'
